// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api_test.Data;

#nullable disable

namespace api_test.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260223125846_addfinalandeditThreeTables")]
    partial class addfinalandeditThreeTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("api_test.Entities.Alert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<int?>("MedicationScheduleId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("UserMedicationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MedicationScheduleId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserMedicationId");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("api_test.Entities.DrugInteraction", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Drug_1_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Drug_2_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Ingredient_1_id")
                        .HasColumnType("int");

                    b.Property<int?>("Ingredient_2_id")
                        .HasColumnType("int");

                    b.Property<string>("Interaction_type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("Ingredient_1_id");

                    b.HasIndex("Ingredient_2_id");

                    b.ToTable("Drug_Interactions");
                });

            modelBuilder.Entity("api_test.Entities.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IngredientName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Ingredient");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("api_test.Entities.MedIngredientLink", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Ingredient_id")
                        .HasColumnType("int");

                    b.Property<int>("Med_id")
                        .HasColumnType("int");

                    b.Property<string>("Strength_unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Strength_value")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("Ingredient_id");

                    b.HasIndex("Med_id");

                    b.ToTable("Med_Ingredients_Link");
                });

            modelBuilder.Entity("api_test.Entities.Medication", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dosage_Form")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trade_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("image_url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Medications");
                });

            modelBuilder.Entity("api_test.Entities.MedicationSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NotificationTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("ReminderSent")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SnoozeCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SnoozedUntil")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TakenAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserMedicationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserMedicationId");

                    b.ToTable("MedicationSchedules");
                });

            modelBuilder.Entity("api_test.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "Patient"
                        });
                });

            modelBuilder.Entity("api_test.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("api_test.Entities.UserMedication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CurrentPillCount")
                        .HasColumnType("int");

                    b.Property<string>("Dosage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DosesPerPeriod")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly?>("FirstDoseTime")
                        .HasColumnType("time");

                    b.Property<int?>("InitialPillCount")
                        .HasColumnType("int");

                    b.Property<int?>("IntervalHours")
                        .HasColumnType("int");

                    b.Property<int?>("LowStockThreshold")
                        .HasColumnType("int");

                    b.Property<int>("MedId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("NotificationActive")
                        .HasColumnType("bit");

                    b.Property<string>("PeriodUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PeriodValue")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MedId");

                    b.HasIndex("UserId");

                    b.ToTable("UserMedications");
                });

            modelBuilder.Entity("api_test.Models.VisitorLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("VisitedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("VisitorLogs");
                });

            modelBuilder.Entity("api_test.Entities.Alert", b =>
                {
                    b.HasOne("api_test.Entities.MedicationSchedule", "MedicationSchedule")
                        .WithMany("Alerts")
                        .HasForeignKey("MedicationScheduleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("api_test.Entities.User", "User")
                        .WithMany("Alerts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("api_test.Entities.UserMedication", "UserMedication")
                        .WithMany("Alerts")
                        .HasForeignKey("UserMedicationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("MedicationSchedule");

                    b.Navigation("User");

                    b.Navigation("UserMedication");
                });

            modelBuilder.Entity("api_test.Entities.DrugInteraction", b =>
                {
                    b.HasOne("api_test.Entities.Ingredient", "Ingredient1")
                        .WithMany()
                        .HasForeignKey("Ingredient_1_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("api_test.Entities.Ingredient", "Ingredient2")
                        .WithMany()
                        .HasForeignKey("Ingredient_2_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Ingredient1");

                    b.Navigation("Ingredient2");
                });

            modelBuilder.Entity("api_test.Entities.MedIngredientLink", b =>
                {
                    b.HasOne("api_test.Entities.Ingredient", "Ingredient")
                        .WithMany("MedLinks")
                        .HasForeignKey("Ingredient_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api_test.Entities.Medication", "Medication")
                        .WithMany("Ingredients")
                        .HasForeignKey("Med_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Medication");
                });

            modelBuilder.Entity("api_test.Entities.MedicationSchedule", b =>
                {
                    b.HasOne("api_test.Entities.UserMedication", "UserMedication")
                        .WithMany("Schedules")
                        .HasForeignKey("UserMedicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserMedication");
                });

            modelBuilder.Entity("api_test.Entities.User", b =>
                {
                    b.HasOne("api_test.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("api_test.Entities.UserMedication", b =>
                {
                    b.HasOne("api_test.Entities.Medication", "Medication")
                        .WithMany("UserMedications")
                        .HasForeignKey("MedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api_test.Entities.User", "User")
                        .WithMany("UserMedications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medication");

                    b.Navigation("User");
                });

            modelBuilder.Entity("api_test.Entities.Ingredient", b =>
                {
                    b.Navigation("MedLinks");
                });

            modelBuilder.Entity("api_test.Entities.Medication", b =>
                {
                    b.Navigation("Ingredients");

                    b.Navigation("UserMedications");
                });

            modelBuilder.Entity("api_test.Entities.MedicationSchedule", b =>
                {
                    b.Navigation("Alerts");
                });

            modelBuilder.Entity("api_test.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("api_test.Entities.User", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("UserMedications");
                });

            modelBuilder.Entity("api_test.Entities.UserMedication", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("Schedules");
                });
#pragma warning restore 612, 618
        }
    }
}
